### ISSUE TITLE
Add the option to annotate with READONLY

### ISSUE THREAD

**Issue by gioppoluca** [losisin/helm-values-schema-json#32]
Could be useful if you manage to add a parsing in the comments to allow for specifying that the element is readonly

**Comment by losisin** [comment]
This sounds like a good idea. Thank you for the suggestion

**Comment by losisin** [comment]
I did some testing and went trough the documentation [here](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-02#section-9.4). Adding `readOnly: true` doesn't provide additional benefit because JSON schema is used for: lint, template, install and upgrade. This property makes more sense in api context like mentioned in release notes https://json-schema.org/understanding-json-schema/reference/annotations

**Comment by gioppoluca** [comment]
I agree that this property is aimed to schema being used in form generation; that is also a fundamental usage for it.

**Comment by gioppoluca** [comment]
BTW having the schema richer with properties does not hinder lint, template and install but opens up the door of generating values.yaml that is at the moment under valued.
I believe that having this plugin enriched with these options could open new paths for development
